create or replace PROCEDURE comprarConMinPrecio(v_cdproducto IN NUMBER)
 IS
V_CDEMPRESA SALVAREZ_PRUEBA.TSIM_PROD_X_EMPRESA.CDEMPRESA%TYPE :='00001';
V_NMCANTIDAD SALVAREZ_PRUEBA.TSIM_PROD_X_EMPRESA.NMCANTIDAD%TYPE := 5;
V_DSERROR VARCHAR2(2);
V_PSVENTA SALVAREZ_PRUEBA.TSIM_PROD_X_EMPRESA.CDEMPRESA%TYPE:= 15;
BEGIN

SELECT CDEMPRESA into V_CDEMPRESA
FROM salvarez_prueba.TSIM_PROD_X_EMPRESA
WHERE PSVENTA = (SELECT MIN(PSVENTA)
	FROM  salvarez_prueba.TSIM_PROD_X_EMPRESA
	WHERE CDPRODUCTO = v_cdproducto
                    AND NMCANTIDAD>= 5)
AND CDPRODUCTO = v_cdproducto ;

SALVAREZ_PRUEBA.SP_COMPRAR_PROD(V_CDEMPRESA, V_CDPRODUCTO,V_NMCANTIDAD,V_DSERROR);
SALVAREZ_PRUEBA.SP_CAMBIO_VALOR_PROD(V_CDPRODUCTO,V_PSVENTA,V_DSERROR);
END comprarConMinPrecio;
